apiVersion: v1
kind: Service
metadata:
  name: order-svc-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 31132
  selector:
    app: order-svc
  type: NodePort
